repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format auto-fix
        entry: clang-format -i
        language: system
        files: \.(c|h)$
        pass_filenames: true
        require_serial: true

      # - id: clang-tidy
      #   name: clang-tidy
      #   entry: clang-tidy
      #   language: system
      #   files: \.(c|h)$
